"""Added monitored_services, circuit_breaks_logs tables 1

Revision ID: 87d357f06fa3
Revises: cff53a6181a2
Create Date: 2025-12-20 17:30:50.114595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d357f06fa3'
down_revision: Union[str, Sequence[str], None] = 'cff53a6181a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'CLOSED', 'HALF_OPEN', name='stateserviceenum'), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('recovery_timeout', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_time', sa.DateTime(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_monitored_services_id'), 'monitored_services', ['id'], unique=False)
    op.create_table('circuit_breaker_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('old_state', sa.Enum('OPEN', 'CLOSED', 'HALF_OPEN', name='stateserviceenum'), nullable=False),
    sa.Column('new_state', sa.Enum('OPEN', 'CLOSED', 'HALF_OPEN', name='stateserviceenum'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['monitored_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_breaker_logs_id'), 'circuit_breaker_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circuit_breaker_logs_id'), table_name='circuit_breaker_logs')
    op.drop_table('circuit_breaker_logs')
    op.drop_index(op.f('ix_monitored_services_id'), table_name='monitored_services')
    op.drop_table('monitored_services')
    # ### end Alembic commands ###
